publish:
    build: ../publish-tar
    mem_limit: 2g
    ports:
        - "4503:4503"

author:
    build: ../author-tar
    mem_limit: 2g
    ports:
        - "4502:4502"
    links:
        - publish

dispatcher:
    build: ../dispatcher-ps
    ports:
        - "80:80"
    links:
        - publish
